[[redirects]]
  from="*starlingedge.io*"
  to="https://www.starlingx.io/"
  status=301
  force=true
[[redirects]]
  from="*starlingx.org*"
  to="https://www.starlingx.io/"
  status=301
  force=true
[[redirects]]
  from="https://starlingedge.io"
  to="https://www.starlingx.io/"
  status=301
  force=true
[[redirects]]
  from="https://www.starlingedge.io"
  to="https://www.starlingx.io/"
  status=301
  force=true
[[redirects]]
  from="https://starlingx.org"
  to="https://www.starlingx.io/"
  status=301
  force=true
[[redirects]]
  from="https://www.starlingx.org"
  to="https://www.starlingx.io/"
  status=301
  force=true
[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  NODE_VERSION = "12.20.1"
  YARN_VERSION = "1.13.0"
  YARN_FLAGS = "--no-ignore-optional"
# Deploy Preview context: all deploys resulting from a pull/merge request will
# inherit these settings.
[context.deploy-preview.environment]
  GATSBY_API_BASE_URL = "https://openstackid-resources.openstack.org"  
  GATSBY_SPONSORED_PROJECT_ID = "6"  
  GATSBY_HOME_SUBPROJECT_ID = "12"
  GATSBY_MEMBERS_SUBPROJECT_ID = "12"
[[headers]]
  for = "/*"
  [headers.values]
  Referrer-Policy = "strict-origin-when-cross-origin"