backend:
  name: github
  repo: StarlingXWeb/starlingx-website
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "site/.vuepress/public/images"
public_folder: "/images"
collections:
  - name: "blog-posts" # Used in routes, e.g., /admin/collections/blog
    label: "Blog Posts" # Used in the UI
    folder: "site/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Author", name: "author", widget: "text" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Cateogry", name: "category", widget: "text" }
    editor:
      preview: false

  - name: "main-pages"
    label: "Main Pages"
    editor:
      preview: false

    files:
      - label: "Home Page"
        name: "home-page"
        file: "site/index.md"
        fields:
          - label: Hero
            name: hero
            widget: object
            fields:
              - { label: "headline", name: headline, widget: string }
              - label: Button
                name: button
                widget: object
                fields:
                  - { label: "title", name: title, widget: string }
                  - { label: "url", name: url, widget: string }
          - label: Values
            name: values
            widget: list
            fields:
              - { label: "Title", name: title, widget: string }
              - { label: "Copy", name: copy, widget: text }
          - label: Get Involved Steps
            name: getInvolvedSteps
            widget: list
            fields:
              - { label: "Title", name: title, widget: string }
              - { label: "Entry", name: entry, widget: text }
              - fields:
                  label: "Link"
                  name: link
                  widget: object
                  fields:
                    - { label: "URL", name: url, widget: string }
                    - { label: "Title", name: title, widget: string }
          - label: Body
            name: body
            widget: markdown

      - label: "Learn"
        name: "learn"
        file: "site/learn/index.md"

        fields:
          - { label: "Description", name: description, widget: string }
          - { label: "Title", name: title, widget: string }
          - { label: "Body", name: body, widget: markdown }

      - label: "Software"
        name: "software"
        file: "site/software/index.md"

        fields:
          - { label: "Description", name: description, widget: string }
          - { label: "Title", name: title, widget: string }
          - { label: "Body", name: body, widget: markdown }

      - label: "Sponsors"
        name: "sponsors"
        file: "site/sponsors/index.md"

        fields:
          - { label: "Description", name: description, widget: string }
          - { label: "Title", name: title, widget: string }
          - { label: "Body", name: body, widget: markdown }

      - label: "Community"
        name: "community"
        file: "site/community/index.md"

        fields:
          - { label: "Description", name: description, widget: string }
          - { label: "Title", name: title, widget: string }
          - { label: "Body", name: body, widget: markdown }

      - label: "FAQs"
        name: "faq"
        file: "site/faq/index.md"

        fields:
          - { label: "Description", name: description, widget: string }
          - { label: "Title", name: title, widget: string }
          - { label: "Body", name: body, widget: markdown }

  - name: "settings"
    label: "Settings"
    files:
      - label: "Top Navigation"
        name: "topnav"
        file: "site/pages.json"
        fields:
          - label: Pages
            name: nav
            widget: list
            fields:
              - { label: Name, name: text, widget: string }
              - { label: Link, name: link, widget: string }

      - label: "Footer Navigation"
        name: "footernav"
        file: "site/footer-nav.json"
        fields:
          - label: About
            name: nav
            widget: list
            fields:
              - { label: Name, name: text, widget: string }
              - { label: Link, name: link, widget: string }
          - label: Connect
            name: nav
            widget: list
            fields:
              - { label: Name, name: text, widget: string }
              - { label: Link, name: link, widget: string }
          - label: Software
            name: nav
            widget: list
            fields:
              - { label: Name, name: text, widget: string }
              - { label: Link, name: link, widget: string }
